repos:
- repo: https://github.com/ambv/black
  rev: 23.1.0
  hooks:
  - id: black
    exclude: disk_image_toolkit/dfxml/
    args: [--safe, --quiet]
    language_version: python3
# - repo: https://gitlab.com/pycqa/flake8
#   rev: 3.8.3
#   hooks:
#   - id: flake8
#     language_version: python3
